# Generated by Django 3.2.7 on 2021-09-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stand_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiestand',
            name='hourly_sales',
        ),
    ]
