# Generated by Django 3.2.7 on 2021-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stand_api', '0002_remove_cookiestand_hourly_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
